### ISSUE TITLE
Usage examples in README.md

### ISSUE THREAD

**Issue by cnzqy1** [scalableminds/webknossos-cuber#311]
Some of the usage examples in README.md are not compatible with the latest version of this package. For example, `python -m wkcuber` does not take `--layer_name` as an option as of v0.5.0.

**Comment by youri-k** [comment]
Sorry that this slipped through. Since `v0.5.0` the new "auto"-conversion feature is used when calling `python -m wkcuber`. This mode automatically detects the input file type and layer names, so the `--layer_name` is not needed anymore. To achieve the old behavior, you can use `python -m wkcuber.convert_image_stack_to_wkw`. I just updated the `README`, but please let me know, if something is still unclear.
