### ISSUE TITLE
Shorthands for read/write in Dataset API

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos-cuber#328]
From the #302 PR I learned about the `Dataset.get_view` shorthand. That made me wonder if a shorthand for the frequently used `read` and `write` methods would also make sense.

```python
ds = WKDataset.create(...)
ds.write(layer='color', layer_category='color', dtype=np.float32, mag='2-2-1', offset=(1024, 1024, 1024), data=data)
data = ds.read(layer='color', mag='2-2-1', offset=(1024, 1024, 1024), shape=(32, 32, 32))
```

Any thoughts? @rschwanhold @philippotto @jstriebel

**Comment by jstriebel** [comment]
I'd find this very useful.

**Comment by jstriebel** [comment]
However, then we'd hide some logic from the user, just to tell them that it's necessary later again, and there would be two ways of doing the same ([`There should be one-- and preferably only one --obvious way to do it.`](https://www.python.org/dev/peps/pep-0020/)). I'm not even sure about `Dataset.get_view` anymore. But if we keep it, reading and writing might be fine as well. I'd say read/write/get_view are the maximum, so that we don't proxy every method in `Dataset`.

**Comment by rschwanhold** [comment]
I will remove the shorthand for `get_view` so that there is only one way.
