### ISSUE TITLE
Downsample image stacks without writing mag1

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos-cuber#97]
When cubing image stacks, it would be great to be able to create downsampled versions (eg 2-2-1) without writing mag 1 to disk.

**Comment by MartinBuessemeyer** [comment]
I have a Question towards this issue:
What is exactly meant with "downsampled versions"?
1. Way of understanding: The Image-Stack has already the format Mag 2-2-1 and therefore it should be written to Mag 2-2-1 instead of Mag 1. Therefore this would (more or less) just require another command line argument.
2. Way of understanding: The Image-Stack has the format Mag 1 and therefore should be directly downsampled to Mag 2-2-1 without Mag 1 being saved to the disk. Then only Mag 2-2-1 should be saved to the disk. Therefore this would require another command line argument and direct "in memory" downsampling.

**Comment by normanrz** [comment]
I meant 2
